SELECT TOP 5 * 
FROM FECHA_6

-- I WANT TO SEE THE DIFFERENCES BETWEEN 'PUNTOS CLARIN' AND 'PUNTOS GRAND DT'

SELECT AVG(PROMEDIO_PUNTOS_CLARIN) AS PROMEDIO_PUNTOS_CLARIN , AVG(PROMEDIO_PUNTOS_GRAN_DT) AS PROMEDIO_PUNTOS_GRAN_DT
FROM fecha_6

-- I CAN SEE THAT IN AVERAGE 'GRAN DT' HAS BIGGER VALUES, BUT HOW MUCH BIGGER?

SELECT (1-(AVG(PROMEDIO_PUNTOS_CLARIN)/AVG(PROMEDIO_PUNTOS_GRAN_DT)))*100 AS DIFERENCIA
FROM fecha_6

-- It´s 8.89% bigger.

-- Which is the average of scores?

SELECT AVG(GOL/6) AS PROMEDIO_GOLES
FROM fecha_6

-- THE AVG IS 0.04 BUT THIS INCLUDE THE GOALKEEPERS TOO SO LETS GROUP BY POSITION

SELECT AVG(GOL/6) AS PROMEDIO_GOLES, POSICION AS PROMEDIO_GOLES
FROM fecha_6
GROUP BY (POSICION)
ORDER BY AVG(GOL) DESC

-- IN AVERAGE THE FORWARDS ARE THE MOST SCORERS WHILE THE KEEPERS ARE THE LESS
-- THE MIDDLES ARE QUITE SIMILAR TO THE DEFENDERS

-- WHICH IS THE AVG OF RED/YELLOW CARDS AND UNDEFEATED HURDLES FOR EACH POSITION?

SELECT AVG(TARJETA_AMARILLA/6) AS AVERAGE_YELL_CARD, AVG(TARJETA_ROJA/6) AS AVERAGE_RED_CARD, AVG(Valla_Invicta/6) AS AVERAGE_UNDEFEATED_HURDLES, POSICION
FROM fecha_6
GROUP BY POSICION

-- WE CAN SEE THAT THE DEFENDERS AND MIDDLES ARE PRONER TO GET A YELLOW AND RED CARDS THAN THE OTHER POSITIONS
-- THE AVG_UNDEFEATED_HURDLES ARE CORRELATED BETWEEN DEFENDERS AND KEEPERS WHICH IS CONSISTEN. THIS AVERAGE MEANS THAT EACH 4 GAMES EVERY DEFENDER/KEEPER HAS IN AVERAGE 1 'CLEAN SHEET'.

-- WHO ARE THE PLAYERS WITH MOST CARDS AND WHICH ARE THEIR SCORES?

SELECT TOP 5 (TARJETA_AMARILLA), POSICION, Nombre_del_jugador,Puntos_Gran_DT,Promedio_Puntos_Gran_DT
FROM fecha_6
ORDER BY Tarjeta_Amarilla DESC

SELECT TOP 5 (Tarjeta_roja), POSICION, Nombre_del_jugador,Puntos_Gran_DT, Promedio_Puntos_Gran_DT
FROM fecha_6
ORDER BY Tarjeta_roja DESC

-- I CAN SEE THAT THE PLAYERS WITH MORE YELLOW CARDS DON´T HAVE A VERY NICE SCORE EACH MATCH WHILE IT ISN´T LIKE THIS WHEN THEY HAVE A RED CARD.

-- WHICH ARE THE TEAMS WITH THE BEST SCORE?

SELECT TOP 5 AVG(Promedio_Puntos_Gran_DT) AS SCORE_AVERAGE, CLUB_DEL_JUGADOR
FROM fecha_6
GROUP BY Club_del_Jugador
ORDER BY AVG(Promedio_Puntos_Gran_DT) DESC

-- THEY ARE RACING,RIVER,UNION,NEWELL'S AND SARMIENTO

-- WHICH ARE THE TEAMS WITH WORST SCORE?

SELECT TOP 5 AVG(Promedio_Puntos_Gran_DT) AS SCORE_AVERAGE, CLUB_DEL_JUGADOR
FROM fecha_6
GROUP BY Club_del_Jugador
ORDER BY AVG(Promedio_Puntos_Gran_DT) ASC

-- THEY ARE CTRL.CORDOBA, ATLETICO TUCUMAN, ROSARIO CENTRAL, GIMNASIA DE LA PLATA AND BOCA (SO STRANGE).

-- WHICH ARE THE TEAMS WITH MOST SCORED?
SELECT TOP 5 SUM(Gol) AS GOALS, CLUB_DEL_JUGADOR
FROM fecha_6
GROUP BY Club_del_Jugador
ORDER BY AVG(Promedio_Puntos_Gran_DT) DESC

-- THEY ARE THE SAME TEAMS WITH HIGHEST SCORE. 

-- AND WHICH ARE THE TEAMS WITH LESS SCORED?
SELECT TOP 5 SUM(Gol) AS GOALS, CLUB_DEL_JUGADOR
FROM fecha_6
GROUP BY Club_del_Jugador
ORDER BY AVG(Promedio_Puntos_Gran_DT) ASC

-- THEY ARE THE SAME TEAMS WITH LOWEST SCORE!!! IT MUST HAVE A CORRELATION BETWEEN GOALS AND GRAN_DT_SCORE.

-- NOW, I WANT TO KNOW WHICH ARE THE PLAYERS WITH HIGHEST SCORES
SELECT TOP 10 Puntos_Gran_DT,Part_jugados,GOL,POSICION,NOMBRE_DEL_JUGADOR, CLUB_DEL_JUGADOR
FROM fecha_6
ORDER BY Puntos_Gran_DT DESC

-- THEY PLAYED EVERY MATCH AND THEY HAVE AT LEAST ONE GOAL

-- NOW I WANT TO SEE WHO ARE THE BEST 5 PLAYERS FOR EACH POSITION
SELECT TOP 3 Puntos_Gran_DT,Part_jugados,GOL,POSICION,NOMBRE_DEL_JUGADOR, CLUB_DEL_JUGADOR
FROM fecha_6
WHERE POSICION = 'ARQUERO'
ORDER BY Puntos_Gran_DT DESC
SELECT TOP 5 Puntos_Gran_DT,Part_jugados,GOL,POSICION,NOMBRE_DEL_JUGADOR, CLUB_DEL_JUGADOR
FROM fecha_6
WHERE POSICION = 'DEFENSOR'
ORDER BY Puntos_Gran_DT DESC
SELECT TOP 5 Puntos_Gran_DT,Part_jugados,GOL,POSICION,NOMBRE_DEL_JUGADOR, CLUB_DEL_JUGADOR
FROM fecha_6
WHERE POSICION = 'VOLANTE'
ORDER BY Puntos_Gran_DT DESC
SELECT TOP 5 Puntos_Gran_DT,Part_jugados,GOL,POSICION,NOMBRE_DEL_JUGADOR, CLUB_DEL_JUGADOR
FROM fecha_6
WHERE POSICION = 'DELANTERO'
ORDER BY Puntos_Gran_DT DESC

-- IN CONCLUSSION:
-- With this first approach to the data, the best lineup will be the one with most forwards because they have more goals and less cards.
-- The teams with the best scores are RACING,RIVER,UNION,NEWELL'S and SARMIENTO so If it is neccesary to get a new player to our team It's a nice idea to choose one from there.
-- If we want a specific player for our team we can select one from the last query
